<?php

/**
 * @file
 * Helper module.
 */

/**
 * Implements hook_preprocess_node().
 */
function dcon_preprocess_node(&$variables) {
  if ($variables['elements']['#view_mode'] === 'search_index') {
    //$variables['page'] = TRUE;
  }
}

/**
 * Implements hook_page_attachments().
 */
function dcon_page_attachments(array &$attachments) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $attachments['#attached']['library'][] = 'dcon/admin-css';
  }
}
